services:
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    ports:
      - '3306:3306'
